// Copy for the Compliance module. Pages import these rather than hardcoding strings.

export const COMPLIANCE_LABELS = {
  PAGE_TITLE: 'Compliance',
  PAGE_SUBTITLE: 'Licences and statutory papers, their current version and renewal dates.',
  DASH: '—',
  FILTER: {
    LABEL: 'Show',
    ACTIVE: 'Active only',
    ALL: 'Including archived',
  },
  ACTIONS: {
    ADD_DOCUMENT: 'Add document',
    UPLOAD_VERSION: 'Upload new version',
    FILE_FIRST_VERSION: 'Upload the first version',
    DOWNLOAD: 'Download',
    EDIT_DETAILS: 'Edit details',
    MAKE_CURRENT: 'Make current',
    SAVE: 'Save',
    CANCEL: 'Cancel',
    UPLOAD: 'Upload',
    CREATE: 'Create document',
    SHOW_HISTORY: (count: number) =>
      count === 1 ? 'Show 1 earlier version' : `Show ${count} earlier versions`,
    HIDE_HISTORY: 'Hide version history',
    NO_HISTORY: 'No earlier versions',
  },
  BADGE: {
    REQUIRED: 'Required',
    OPTIONAL: 'Optional',
    ARCHIVED: 'Archived',
    CURRENT: 'Current',
    SUPERSEDED: 'Superseded',
  },
  STATE: {
    NO_VERSION: 'Nothing filed',
    NO_EXPIRY: 'Does not expire',
    EXPIRED: (days: number) => (days === 1 ? 'Expired yesterday' : `Expired ${days} days ago`),
    EXPIRES_TODAY: 'Expires today',
    EXPIRES_IN: (days: number) => (days === 1 ? 'Expires tomorrow' : `Expires in ${days} days`),
  },
  FIELDS: {
    TYPE: 'Document type',
    CATEGORY: 'Category',
    TITLE: 'Title',
    REFERENCE_NUMBER: 'Reference number',
    NOTES: 'Notes',
    VERSION: 'Version',
    FILE: 'File',
    FILE_NAME: 'File name',
    VALID_FROM: 'Valid from',
    VALID_TO: 'Valid to',
    ISSUED_BY: 'Issued by',
    UPLOADED_AT: 'Uploaded',
    UPLOADED_BY: 'Uploaded by',
    RENEWAL_CYCLE: 'Renewal cycle',
  },
  HINTS: {
    // The single most important piece of copy on the page: valid_to is optional.
    VALID_TO_OPTIONAL: 'Optional — leave blank if this document does not expire.',
    VALID_FROM_REQUIRED: 'Required.',
    FILE_RULES: 'PDF, JPG or PNG. Maximum 20MB.',
    CURRENT_VERSION: 'This is the version currently in force.',
    HISTORICAL_VERSION: 'Superseded — kept for the record. Dates can still be corrected.',
    NOTHING_FILED: 'No file has been uploaded for this document yet.',
    NOTHING_FILED_TYPE: 'Nothing has been filed for this document type yet.',
    MAKE_CURRENT: 'Point this document at this version instead. Changes the expiry reminders.',
    ARCHIVED_TYPE: 'This document type is archived. New documents cannot be filed against it.',
    RENEWAL_MONTHS: (months: number) => `Renews every ${months} months`,
    VERSION_COUNT: (count: number) => (count === 1 ? '1 version' : `${count} versions`),
    // The API returns a users.id and never expands a name.
    USER_REF: (id: number) => `User #${id}`,
    VERSION_NO: (versionNo: number) => `Version ${versionNo}`,
  },
  MODALS: {
    UPLOAD_TITLE: 'Upload a new version',
    uploadSubtitle: (title: string) => `${title} — the uploaded file becomes the current version.`,
    CREATE_TITLE: 'Add a compliance document',
    CREATE_SUBTITLE:
      'Pick the document type and give it a title. You can upload the file straight after.',
    EDIT_TITLE: 'Edit version details',
    editSubtitle: (versionNo: number) => `Version ${versionNo} — the file itself cannot be changed.`,
    NO_FILE_CHOSEN: 'No file chosen',
    CHOOSE_FILE: 'Choose file',
  },
  EMPTY: {
    NO_TYPES: 'No document types are set up for this pharmacy yet.',
    NO_DOCUMENTS: 'Nothing has been filed yet. Add your first compliance document.',
  },
  VALIDATION: {
    FILE_REQUIRED: 'Choose a PDF, JPG or PNG file to upload.',
    FILE_TOO_LARGE: 'File too large. Max 20MB.',
    FILE_TYPE: 'Unsupported file type. Allowed: PDF, JPG, PNG.',
    VALID_FROM_REQUIRED: 'Valid from is required.',
    VALID_FROM_NOT_CLEARABLE: 'Valid from cannot be cleared — enter a date or cancel.',
    VALID_TO_BEFORE_FROM: 'Valid to must not be earlier than valid from.',
    TITLE_REQUIRED: 'Title is required.',
    TYPE_REQUIRED: 'Choose a document type.',
    NO_CHANGES: 'Nothing has changed.',
  },
  TOAST: {
    DOCUMENT_CREATED: 'Document created. Upload the first version to complete it.',
    VERSION_UPLOADED: 'New version uploaded and made current.',
    VERSION_UPDATED: 'Version details updated.',
    MADE_CURRENT: 'That version is now the current one.',
    DOWNLOAD_ERROR: 'Could not download that file.',
    LOAD_ERROR: 'Could not load compliance documents.',
    HISTORY_ERROR: 'Could not load the version history.',
    CREATE_ERROR: 'Could not create the document.',
    UPLOAD_ERROR: 'Could not upload the version.',
    UPDATE_ERROR: 'Could not save the version details.',
    MAKE_CURRENT_ERROR: 'Could not change the current version.',
  },
  PAGING: {
    LOAD_MORE: 'Load more',
    showingAtLeast: (shown: number) => `Showing ${shown} — there may be more.`,
    showing: (shown: number, total: number) =>
      shown >= total ? `Showing all ${total}` : `Showing ${shown} of ${total}`,
    // The server hard-caps a page at 200 rows; say so rather than letting a
    // compliance list look complete when it is not.
    documentsCapped: (max: number) =>
      `Showing the first ${max}. Filter by document type or status to see the rest.`,
    versionsCapped: (max: number) => `Showing the first ${max} versions.`,
    TYPE_FILTER: 'Document type',
    ALL_TYPES: 'All types',
  },
  NAV: {
    DOCUMENTS: 'Documents',
    CALENDAR: 'Calendar',
    SETTINGS: 'Settings',
  },
  CALENDAR: {
    TITLE: 'Compliance calendar',
    SUBTITLE: 'Renewals due, lapsed licences and papers still to be filed.',
    LOAD_ERROR: 'Could not load the compliance calendar.',
    windowLabel: (from: string, to: string) => `Showing ${from} to ${to}`,
    OVERDUE: 'Overdue',
    OVERDUE_HINT: 'Lapsed licences. These are always shown, whatever month you are viewing.',
    UPCOMING: 'Upcoming in this window',
    NOTHING_FILED: 'Nothing filed yet',
    NOTHING_FILED_HINT: 'Required document types with no document at all.',
    NO_EXPIRY: 'Documents that do not expire',
    NO_EXPIRY_HINT: 'Filed and in force. Not calendar events — they have no renewal date.',
    ON_DATE: (date: string) => `On ${date}`,
    CLEAR_DATE: 'Show the whole window',
    NOTHING_DUE: 'Nothing due in this window.',
    NOTHING_OVERDUE: 'Nothing is overdue.',
    ALL_FILED: 'Every required document type has something filed.',
    NONE: 'None.',
    ALL_CLEAR: 'Nothing needs your attention right now.',
    NEXT_ACTION: 'Next action',
    FILE_IT: 'File this document',
    OPEN_DOCUMENT: 'Open document',
    NOT_FILED: 'Not filed yet',
    NO_EXPIRY_STATE: 'Does not expire',
  },
  TYPES: {
    TITLE: 'Document types',
    SUBTITLE:
      'The papers this pharmacy must keep. Archiving a type keeps the documents already filed against it.',
    ADD: 'Add document type',
    EDIT_TITLE: 'Edit document type',
    ADD_TITLE: 'Add a document type',
    KEY: 'Key',
    KEY_HINT: 'Lowercase letters, numbers and underscore. Cannot be changed later.',
    NAME: 'Name',
    DESCRIPTION: 'Description',
    CATEGORY: 'Category',
    IS_REQUIRED: 'Required for this pharmacy',
    IS_REQUIRED_HINT: 'Required types raise a reminder when nothing is filed against them.',
    VALIDITY_MONTHS: 'Renewal cycle (months)',
    VALIDITY_MONTHS_HINT: 'Leave blank when there is no fixed renewal cycle.',
    ARCHIVE: 'Archive',
    RESTORE: 'Restore',
    ARCHIVE_CONFIRM: 'Archive this document type? Documents already filed against it are kept.',
    KEY_REQUIRED: 'Key must be 2-64 characters of a-z, 0-9 and underscore.',
    NAME_REQUIRED: 'Name is required.',
    VALIDITY_INVALID: 'Renewal cycle must be a whole number of months between 1 and 600.',
    CREATED: 'Document type created.',
    UPDATED: 'Document type updated.',
    ARCHIVED: 'Document type archived.',
    RESTORED: 'Document type restored.',
    CREATE_ERROR: 'Could not save the document type.',
    ARCHIVE_ERROR: 'Could not archive the document type.',
    // The 409 the backend now answers with { error, id, status } — an archived type
    // with the same key must be RESTORED, never re-created.
    RESTORE_CONFLICT: 'Restore the archived type',
    LOAD_ERROR: 'Could not load document types.',
    EMPTY: 'No document types yet.',
  },
  REMINDERS: {
    TITLE: 'Renewal reminders',
    SUBTITLE:
      'How many days before a document expires the reminders start. This is an organisation-wide setting — it changes the reminders for everyone in this pharmacy, not just you.',
    ORG_DEFAULT: 'Organisation default',
    USING_DEFAULTS: 'Using the shipped defaults — nothing has been saved yet.',
    LEAD_DAYS: 'Days before expiry',
    LEAD_DAYS_HINT:
      'Between 1 and 6 values, each 1-3650 days. The largest is when warnings start; the smallest is when they escalate.',
    OVERRIDES: 'Per-type overrides',
    OVERRIDES_HINT: 'Types without an override follow the organisation default.',
    ADD_OVERRIDE: 'Add an override',
    REMOVE_OVERRIDE: 'Use the default',
    NO_OVERRIDES: 'No overrides — every type uses the organisation default.',
    READ_ONLY: 'Only an owner or admin can change these reminders.',
    SAVED: 'Reminder settings saved.',
    SAVE_ERROR: 'Could not save the reminder settings.',
    LOAD_ERROR: 'Could not load the reminder settings.',
    INVALID: 'Enter 1 to 6 whole numbers between 1 and 3650, separated by commas.',
    NO_CHANGES: 'Nothing has changed.',
  },
  DOCUMENT_EDIT: {
    TITLE: 'Edit document',
    ACTION: 'Edit document',
    STATUS: 'Status',
    ACTIVE: 'Active',
    ARCHIVED: 'Archived',
    ARCHIVE_HINT: 'An archived document is hidden from the active list and stops raising reminders.',
    SAVED: 'Document updated.',
    ERROR: 'Could not update the document.',
  },
} as const;

export type ComplianceLabels = typeof COMPLIANCE_LABELS;
