// Copy for the Compliance module. Pages import these rather than hardcoding strings.

export const COMPLIANCE_LABELS = {
  PAGE_TITLE: 'Compliance',
  PAGE_SUBTITLE: 'Licences and statutory papers, their current version and renewal dates.',
  DASH: '—',
  FILTER: {
    LABEL: 'Show',
    ACTIVE: 'Active only',
    ALL: 'Including archived',
  },
  ACTIONS: {
    ADD_DOCUMENT: 'Add document',
    UPLOAD_VERSION: 'Upload new version',
    FILE_FIRST_VERSION: 'Upload the first version',
    DOWNLOAD: 'Download',
    EDIT_DETAILS: 'Edit details',
    MAKE_CURRENT: 'Make current',
    SAVE: 'Save',
    CANCEL: 'Cancel',
    UPLOAD: 'Upload',
    CREATE: 'Create document',
    SHOW_HISTORY: (count: number) =>
      count === 1 ? 'Show 1 earlier version' : `Show ${count} earlier versions`,
    HIDE_HISTORY: 'Hide version history',
    NO_HISTORY: 'No earlier versions',
  },
  BADGE: {
    REQUIRED: 'Required',
    OPTIONAL: 'Optional',
    ARCHIVED: 'Archived',
    CURRENT: 'Current',
    SUPERSEDED: 'Superseded',
  },
  STATE: {
    NO_VERSION: 'Nothing filed',
    NO_EXPIRY: 'Does not expire',
    EXPIRED: (days: number) => (days === 1 ? 'Expired yesterday' : `Expired ${days} days ago`),
    EXPIRES_TODAY: 'Expires today',
    EXPIRES_IN: (days: number) => (days === 1 ? 'Expires tomorrow' : `Expires in ${days} days`),
  },
  FIELDS: {
    TYPE: 'Document type',
    CATEGORY: 'Category',
    TITLE: 'Title',
    REFERENCE_NUMBER: 'Reference number',
    NOTES: 'Notes',
    VERSION: 'Version',
    FILE: 'File',
    FILE_NAME: 'File name',
    VALID_FROM: 'Valid from',
    VALID_TO: 'Valid to',
    ISSUED_BY: 'Issued by',
    UPLOADED_AT: 'Uploaded',
    UPLOADED_BY: 'Uploaded by',
    RENEWAL_CYCLE: 'Renewal cycle',
  },
  HINTS: {
    // The single most important piece of copy on the page: valid_to is optional.
    VALID_TO_OPTIONAL: 'Optional — leave blank if this document does not expire.',
    VALID_FROM_REQUIRED: 'Required.',
    FILE_RULES: 'PDF, JPG or PNG. Maximum 20MB.',
    CURRENT_VERSION: 'This is the version currently in force.',
    HISTORICAL_VERSION: 'Superseded — kept for the record. Dates can still be corrected.',
    NOTHING_FILED: 'No file has been uploaded for this document yet.',
    NOTHING_FILED_TYPE: 'Nothing has been filed for this document type yet.',
    MAKE_CURRENT: 'Point this document at this version instead. Changes the expiry reminders.',
    MAKE_CURRENT_DENIED: 'Only an owner or admin can change which version is current.',
    ARCHIVED_TYPE: 'This document type is archived. New documents cannot be filed against it.',
    RENEWAL_MONTHS: (months: number) => `Renews every ${months} months`,
    VERSION_COUNT: (count: number) => (count === 1 ? '1 version' : `${count} versions`),
    // The API returns a users.id and never expands a name.
    USER_REF: (id: number) => `User #${id}`,
    VERSION_NO: (versionNo: number) => `Version ${versionNo}`,
  },
  MODALS: {
    UPLOAD_TITLE: 'Upload a new version',
    uploadSubtitle: (title: string) => `${title} — the uploaded file becomes the current version.`,
    CREATE_TITLE: 'Add a compliance document',
    CREATE_SUBTITLE:
      'Pick the document type and give it a title. You can upload the file straight after.',
    EDIT_TITLE: 'Edit version details',
    editSubtitle: (versionNo: number) => `Version ${versionNo} — the file itself cannot be changed.`,
    NO_FILE_CHOSEN: 'No file chosen',
    CHOOSE_FILE: 'Choose file',
  },
  EMPTY: {
    NO_TYPES: 'No document types are set up for this pharmacy yet.',
    NO_DOCUMENTS: 'Nothing has been filed yet. Add your first compliance document.',
  },
  VALIDATION: {
    FILE_REQUIRED: 'Choose a PDF, JPG or PNG file to upload.',
    FILE_TOO_LARGE: 'File too large. Max 20MB.',
    FILE_TYPE: 'Unsupported file type. Allowed: PDF, JPG, PNG.',
    VALID_FROM_REQUIRED: 'Valid from is required.',
    VALID_TO_BEFORE_FROM: 'Valid to must not be earlier than valid from.',
    TITLE_REQUIRED: 'Title is required.',
    TYPE_REQUIRED: 'Choose a document type.',
    NO_CHANGES: 'Nothing has changed.',
  },
  TOAST: {
    DOCUMENT_CREATED: 'Document created. Upload the first version to complete it.',
    VERSION_UPLOADED: 'New version uploaded and made current.',
    VERSION_UPDATED: 'Version details updated.',
    MADE_CURRENT: 'That version is now the current one.',
    DOWNLOAD_ERROR: 'Could not download that file.',
    LOAD_ERROR: 'Could not load compliance documents.',
    HISTORY_ERROR: 'Could not load the version history.',
    CREATE_ERROR: 'Could not create the document.',
    UPLOAD_ERROR: 'Could not upload the version.',
    UPDATE_ERROR: 'Could not save the version details.',
    MAKE_CURRENT_ERROR: 'Could not change the current version.',
  },
} as const;

export type ComplianceLabels = typeof COMPLIANCE_LABELS;
