export const INVENTORY_LABELS = {
  pageTitle: "Inventory",
  lowStockTab: "Low Stock",
  excessStockTab: "Excess Stock",
  expiredStockTab: "Expired Stock",
  nearExpiryStockTab: "Near Expiry Stock",
  totalLowStock:"Total Low Stock",
  totalExcessStock: "Total Excess Stock",
  totalExpiredStock: "Total Expired Stock",
  totalNearExpiryStock: "Total Near Expiry Stock",
  loadingData: "Loading data...",
  error: "Error:",
  productNameHeader: "Product Name",
  currentQuantityHeader: "Current Qty",
  minimumQuantityHeader: "Minimum Qty",
  maximumQuantityHeader: "Maximum Qty",
  batchNoHeader: "Batch No",
  expiryDateHeader: "Expiry Date",
  daysPastExpiryHeader: "No Days Past",
  daysToExpiryHeader: "No of days to expiry",
  brandHeader: "Brand",
  typeHeader: "Type",
  addToCartAltText: "Add to cart",
  threeMonths: "3 months",
  oneMonth: "1 month",
};

export const FILTER_OPTIONS = {
  name: "Product Name",
  currentQuantity: "Current Quantity",
  minQuantity: "Minimum Quantity",
  maxQuantity: "Maximum Quantity",
  batchNumber: "Batch No",
  expiryDate: "Expiry Date",
  daysPastExpiry: "No Days Past",
  daysToExpiry: "No of days to expiry",
  brand: "Brand",
  type: "Type"
};