export const INVENTORY_LABELS = {
  pageTitle: "Inventory",
  lowStockTab: "Low Stock",
  excessStockTab: "Excess Stock",
  expiredStockTab: "Expired Stock",
  nearExpiryStockTab: "Near Expiry Stock",
  stockTab: "Stock",
  totalLowStock:"Low Stock",
  totalExcessStock: "Excess Stock",
  totalExpiredStock: "Expired Stock",
  totalNearExpiryStock: "Near Expiry Stock",
  totalStock: "Stock",
  loadingData: "Loading data...",
  error: "Error:",
  productNameHeader: "Product Name",
  currentQuantityHeader: "Current Qty",
  minimumQuantityHeader: "Min Qty",
  maximumQuantityHeader: "Max Qty",
  batchNoHeader: "Batch No",
  expiryDateHeader: "Expiry Date",
  daysPastExpiryHeader: "No Days Past",
  daysToExpiryHeader: "No of days to expiry",
  brandHeader: "Brand",
  typeHeader: "Type",
  addToCartAltText: "Add to cart",
  threeMonths: "3 months",
  oneMonth: "1 month",
};

export const FILTER_OPTIONS = {
  name: "Product Name",
  currentQuantity: "Current Qty",
  minQuantity: "Min Qty",
  maxQuantity: "Max Qty",
  batchNumber: "Batch No",
  expiryDate: "Expiry Date",
  daysPastExpiry: "No Days Past",
  daysToExpiry: "No of days to expiry",
  brand: "Brand",
  type: "Type"
};