export const ORG_LABELS = {
  DASHBOARD: {
    PAGE_TITLE: 'Org Management',
    SUBTITLE: 'Manage roles, modules and your organization profile.',
    SECTIONS: {
      ROLES: {
        TITLE: 'Role Management',
        DESC: 'Assign org and per-module roles to your team members.',
        ACTION: 'Manage Roles',
      },
      MODULES: {
        TITLE: 'Modules',
        DESC: 'Enable or disable optional product modules for your organization.',
        ACTION: 'Manage Modules',
      },
      SETTINGS: {
        TITLE: 'Organization Settings',
        DESC: 'Update your organization name, country, timezone and currency.',
        ACTION: 'Open Settings',
      },
      LABEL: {
        TITLE: 'Org Label',
        DESC: 'Upload the logo that represents your organization across the app.',
        ACTION: 'Manage Label',
      },
    },
  },
  MODULES: {
    PAGE_TITLE: 'Modules',
    SUBTITLE: 'Enable or disable optional product modules for your organization.',
    CORE_TAG: 'Core',
    LOADING: 'Loading modules…',
    LOAD_ERROR: 'Failed to load modules.',
    TOGGLE_ERROR: 'Failed to update module.',
    ENABLED_SUCCESS: (label: string) => `${label} enabled.`,
    DISABLED_SUCCESS: (label: string) => `${label} disabled.`,
  },
  SETTINGS: {
    PAGE_TITLE: 'Organization Settings',
    SUBTITLE: 'Your organization profile.',
    LOADING: 'Loading organization…',
    LOAD_ERROR: 'Failed to load organization.',
    SAVE_SUCCESS: 'Organization updated.',
    SAVE_ERROR: 'Failed to update organization.',
    READ_ONLY_NOTE: 'Only a superadmin can edit organization settings.',
    FIELDS: {
      NAME: 'Organization Name',
      SLUG: 'Slug',
      STATUS: 'Status',
      COUNTRY: 'Country',
      TIMEZONE: 'Timezone',
      CURRENCY: 'Currency',
    },
    SAVE_BUTTON: 'Save Changes',
  },
  LABEL: {
    PAGE_TITLE: 'Org Label',
    SUBTITLE: 'Upload the logo that represents your organization across the app.',
    READ_ONLY_NOTE: 'Only a superadmin can change the organization logo.',
    LOADING: 'Loading organization…',
    LOAD_ERROR: 'Failed to load organization.',
    CURRENT_HEADING: 'Current logo',
    DEFAULT_CAPTION: 'Default logo',
    PENDING_CAPTION: 'Pending upload',
    CHOOSE_BUTTON: 'Choose image',
    UPLOAD_BUTTON: 'Save logo',
    REMOVE_BUTTON: 'Remove logo',
    HINT: 'PNG, JPEG, WebP or SVG. Max 1MB.',
    UPLOAD_SUCCESS: 'Organization logo updated.',
    UPLOAD_ERROR: 'Failed to update organization logo.',
    REMOVE_SUCCESS: 'Organization logo removed.',
    REMOVE_ERROR: 'Failed to remove organization logo.',
    INVALID_TYPE: 'Unsupported file type. Use PNG, JPEG, WebP or SVG.',
    OVERSIZE: 'Image is too large. Maximum size is 1MB.',
    READ_ERROR: 'Could not read the selected file.',
    REMOVE_CONFIRM_TITLE: 'Remove logo',
    REMOVE_CONFIRM_MESSAGE: 'Remove the current organization logo? The default logo will be shown instead.',
    ACCEPTED_TYPES: ['image/png', 'image/jpeg', 'image/webp', 'image/svg+xml'] as const,
    MAX_BYTES: 1024 * 1024,
  },
} as const;
