// Centralised labels for the Outpatient (OPD) module. Pages import these rather
// than hardcoding strings (per src/config conventions).
export const OPD_LABELS = {
  APPOINTMENTS: {
    PAGE_TITLE: 'Appointments',
    SUBTITLE: 'View, book and manage outpatient appointments.',
    BOOK_BUTTON: 'Book Appointment',
    SEARCH_PLACEHOLDER: 'Search by patient name…',
    TABS: { UPCOMING: 'Upcoming', HISTORICAL: 'Historical' },
    FILTERS: {
      FROM: 'From',
      TO: 'To',
      DOCTOR: 'Doctor',
      SERVICE: 'Service',
      STATUS: 'Status',
      TYPE: 'Type',
      SOURCE: 'Source',
      ALL: 'All',
      CLEAR: 'Clear filters',
    },
    TABLE: {
      PATIENT: 'PATIENT',
      TYPE: 'TYPE',
      PROVIDER: 'PROVIDER / SERVICE',
      DATETIME: 'DATE & TIME',
      STATUS: 'STATUS',
      SOURCE: 'SOURCE',
      ACTIONS: 'ACTIONS',
    },
    ACTIONS: {
      VIEW: 'View',
      RESCHEDULE: 'Reschedule',
      CANCEL: 'Cancel',
      CHECK_IN: 'Check-in',
    },
    MESSAGES: {
      LOADING: 'Loading appointments…',
      ERROR: 'Failed to load appointments. Please try again.',
      EMPTY: 'No appointments found.',
      CHECK_IN_SUCCESS: 'Patient checked in.',
      CHECK_IN_ERROR: 'Failed to check in. Please try again.',
      CANCEL_SUCCESS: 'Appointment cancelled.',
      CANCEL_ERROR: 'Failed to cancel appointment. Please try again.',
      RESCHEDULE_SUCCESS: 'Appointment rescheduled.',
      RESCHEDULE_ERROR: 'Failed to reschedule. Please try again.',
      SLOT_TAKEN: 'That slot was just taken. Please pick another.',
      STATUS_SUCCESS: 'Appointment status updated.',
      STATUS_ERROR: 'Failed to update status. Please try again.',
    },
    VIEW_DIALOG: {
      TITLE: 'Appointment details',
      PATIENT: 'Patient',
      PHONE: 'Phone',
      TYPE: 'Type',
      PROVIDER: 'Provider / Service',
      DATETIME: 'Scheduled',
      STATUS: 'Status',
      SOURCE: 'Source',
      TOKEN: 'Token number',
      CHECK_IN_AT: 'Checked in at',
      CANCEL_REASON: 'Cancellation reason',
      CHANGE_STATUS: 'Change status',
      NO_TRANSITIONS: 'No further status changes are available.',
      CLOSE: 'Close',
    },
    RESCHEDULE_DIALOG: {
      TITLE: 'Reschedule appointment',
      DATE: 'New date',
      SLOT: 'New slot',
      NO_SLOTS: 'No slots available for this date.',
      CONFIRM: 'Reschedule',
      CANCEL: 'Cancel',
    },
    CANCEL_DIALOG: {
      TITLE: 'Cancel appointment',
      MESSAGE: 'Are you sure you want to cancel this appointment?',
      REASON: 'Reason (optional)',
      CONFIRM: 'Cancel appointment',
      DISMISS: 'Keep appointment',
    },
  },
  BOOKING: {
    PAGE_TITLE: 'Book Appointment',
    STEPS: { PATIENT: 'Patient', CATEGORY: 'Category', PROVIDER: 'Provider & Slot', CONFIRM: 'Confirm' },
    CATEGORY: {
      OPD: 'Outpatient (OPD)',
      IPD: 'Inpatient (IPD)',
      IPD_DISABLED: 'Coming soon',
      CONSULTATION: 'Consultation',
      SERVICE: 'Service',
      CHOOSE: 'Choose a category',
    },
    PROVIDER: {
      DOCTOR: 'Doctor',
      SERVICE: 'Service',
      DATE: 'Date',
      SLOTS: 'Available slots',
      NO_SLOTS: 'No slots available for this date.',
      PICK_PROVIDER: 'Select a doctor to view slots.',
      PICK_SERVICE: 'Select a service to view slots.',
    },
    CONFIRM: {
      TITLE: 'Review & confirm',
      PATIENT: 'Patient',
      TYPE: 'Type',
      PROVIDER: 'Provider / Service',
      DATETIME: 'Date & time',
      BOOK: 'Confirm booking',
    },
    NAV: { BACK: 'Back', NEXT: 'Next' },
    MESSAGES: {
      SUCCESS: 'Appointment booked.',
      ERROR: 'Failed to book appointment. Please try again.',
      SLOT_TAKEN: 'That slot was just taken. We refreshed the list — please pick another.',
    },
  },
  SERVICE_ORDERS: {
    PAGE_TITLE: 'Service Orders',
    SUBTITLE: 'Track patient service orders and their sessions.',
    NEW_BUTTON: 'New Service Order',
    TABS: {
      ALL: 'All',
      PENDING: 'Pending',
      SCHEDULED: 'Scheduled',
      COMPLETED: 'Completed',
      CANCELLED: 'Cancelled',
    },
    TABLE: {
      PATIENT: 'PATIENT',
      SERVICE: 'SERVICE',
      SESSIONS: 'SESSIONS',
      STATUS: 'STATUS',
      CREATED: 'CREATED',
      ACTIONS: 'ACTIONS',
    },
    SESSIONS_LEFT: 'left',
    ACTIONS: {
      BOOK: 'Book session',
      COMPLETE: 'Mark session complete',
      CANCEL: 'Cancel order',
      VIEW: 'View',
    },
    STATUS_LABELS: {
      pending: 'Pending',
      scheduled: 'Scheduled',
      completed: 'Completed',
      cancelled: 'Cancelled',
    } as Record<string, string>,
    NEW_DIALOG: {
      TITLE: 'New service order',
      PATIENT: 'Patient',
      SERVICE: 'Service',
      PICK_SERVICE: 'Select a service',
      TOTAL_SESSIONS: 'Total sessions',
      NOTES: 'Notes (optional)',
      CREATE: 'Create order',
      CANCEL: 'Cancel',
      VALIDATION: 'Select a patient, a service and at least 1 session.',
    },
    VIEW_DIALOG: {
      TITLE: 'Service order details',
      PATIENT: 'Patient',
      PHONE: 'Phone',
      SERVICE: 'Service',
      STATUS: 'Status',
      SESSIONS: 'Sessions',
      NOTES: 'Notes',
      CANCEL_REASON: 'Cancellation reason',
      APPOINTMENTS: 'Sessions booked',
      NO_APPOINTMENTS: 'No sessions booked yet.',
      REOPEN: 'Reopen order',
      CLOSE: 'Close',
    },
    CANCEL_DIALOG: {
      TITLE: 'Cancel service order',
      MESSAGE: 'Are you sure you want to cancel this service order?',
      REASON: 'Reason (optional)',
      CONFIRM: 'Cancel order',
      DISMISS: 'Keep order',
    },
    MESSAGES: {
      ERROR: 'Failed to load service orders. Please try again.',
      EMPTY: 'No service orders found.',
      CREATE_SUCCESS: 'Service order created.',
      CREATE_ERROR: 'Failed to create service order. Please try again.',
      COMPLETE_SUCCESS: 'Session marked complete.',
      COMPLETE_ERROR: 'Failed to complete session. Please try again.',
      CANCEL_SUCCESS: 'Service order cancelled.',
      CANCEL_ERROR: 'Failed to cancel service order. Please try again.',
      REOPEN_SUCCESS: 'Service order reopened.',
      REOPEN_ERROR: 'Failed to reopen service order. Please try again.',
    },
  },
  WALK_IN: {
    PAGE_TITLE: 'Walk-in Registration',
    SUBTITLE: 'Register a walk-in patient and issue a queue token.',
    DOCTOR: 'Doctor',
    DOCTOR_HINT: 'Select the doctor the patient will see.',
    REGISTER: 'Register Walk-in',
    TOKEN_TITLE: 'Walk-in registered',
    TOKEN_LABEL: 'Token number',
    TOKEN_DONE: 'Done',
    MESSAGES: {
      SUCCESS: 'Walk-in registered.',
      ERROR: 'Failed to register walk-in. Please try again.',
      NOT_ACCEPTING: 'This doctor is not accepting walk-ins right now.',
    },
  },
  PATIENT_PICKER: {
    SEARCH_PLACEHOLDER: 'Search patient by name, phone or MRN…',
    NO_RESULTS: 'No matching patients. Create a new one below.',
    SELECTED: 'Selected patient',
    CHANGE: 'Change',
    CREATE_TOGGLE: 'Create new patient',
    CREATE_TITLE: 'New patient',
    CREATE: 'Create patient',
    CANCEL: 'Cancel',
    FIELDS: {
      NAME: 'Full name',
      GENDER: 'Gender',
      PHONE: 'Phone',
      EMAIL: 'Email',
      MRN: 'MRN',
      ADDRESS: 'Address',
    },
    NAME_REQUIRED: 'Name is required.',
    CREATE_ERROR: 'Failed to create patient. Please try again.',
  },
  QUEUE: {
    PAGE_TITLE: 'Live Queue',
    SUBTITLE: 'Manage today’s waiting list and call patients in.',
    DOCTOR: 'Doctor',
    DOCTOR_LOCKED_HINT: 'Showing your own queue.',
    PICK_DOCTOR: 'Select a doctor to view their live queue.',
    NOT_LINKED: 'Your account is not linked to a provider. Ask an admin to link it.',
    CALL_NEXT: 'Call Next',
    NOW_SERVING: 'Now serving',
    WAITING: 'Waiting',
    POSITION: 'POS',
    TOKEN: 'TOKEN',
    PATIENT: 'PATIENT',
    STATUS: 'STATUS',
    SOURCE: 'SOURCE',
    WAIT: 'CHECK-IN / WAIT',
    ACTIONS: 'ACTIONS',
    ACTIONS_LABELS: {
      MOVE_UP: 'Move up',
      MOVE_DOWN: 'Move down',
      CHECK_IN: 'Check-in',
      SKIP: 'Skip',
      NO_SHOW: 'No-show',
      CANCEL_WALK_IN: 'Cancel walk-in',
    },
    NO_SHOW_DIALOG: {
      TITLE: 'Mark as no-show',
      MESSAGE: 'Mark this patient as a no-show? They will be removed from the queue.',
      CONFIRM: 'Mark no-show',
      DISMISS: 'Keep in queue',
    },
    CANCEL_WALK_IN_DIALOG: {
      TITLE: 'Cancel walk-in',
      MESSAGE: 'Cancel this walk-in registration?',
      CONFIRM: 'Cancel walk-in',
      DISMISS: 'Keep',
    },
    MESSAGES: {
      LOADING: 'Loading queue…',
      ERROR: 'Failed to load the queue. Please try again.',
      EMPTY: 'No patients in the queue.',
      EMPTY_NO_DOCTOR: 'Select a doctor to view their queue.',
      CALL_NEXT_SUCCESS: 'Next patient called.',
      CALL_NEXT_EMPTY: 'Queue is empty — no one to call.',
      CALL_NEXT_ERROR: 'Failed to call next patient. Please try again.',
      CHECK_IN_SUCCESS: 'Patient checked in.',
      CHECK_IN_ERROR: 'Failed to check in. Please try again.',
      SKIP_SUCCESS: 'Patient skipped.',
      SKIP_ERROR: 'Failed to skip patient. Please try again.',
      NO_SHOW_SUCCESS: 'Marked as no-show.',
      NO_SHOW_ERROR: 'Failed to mark no-show. Please try again.',
      CANCEL_SUCCESS: 'Walk-in cancelled.',
      CANCEL_ERROR: 'Failed to cancel walk-in. Please try again.',
      REORDER_SUCCESS: 'Queue reordered.',
      REORDER_ERROR: 'Failed to reorder queue. Please try again.',
    },
  },
  SLOT_CONFIG: {
    PAGE_TITLE: 'Slot Configuration',
    SUBTITLE: 'Set provider availability, manage services and link provider accounts.',
    SECTIONS: {
      AVAILABILITY: { TITLE: 'Provider Availability', DESC: 'Define recurring or one-off availability windows.' },
      SERVICES: { TITLE: 'Services', DESC: 'Create and manage bookable services.' },
      LINK: { TITLE: 'Link Provider Accounts', DESC: 'Connect a doctor record to a user login.' },
    },
    PROVIDER: 'Doctor',
    SERVICE: 'Service',
    PICK_PROVIDER: 'Select a doctor to view availability.',
    PICK_SERVICE: 'Select a service to view availability.',
    DOCTOR_LOCKED_HINT: 'Managing your own availability.',
    NOT_LINKED: 'Your account is not linked to a provider. Ask an admin to link it before setting availability.',
    READ_ONLY_HINT: 'You can view availability but not edit it.',
    ADD: 'Add availability',
    TABLE: {
      WHEN: 'WHEN',
      TIME: 'TIME',
      DURATION: 'SLOT (MIN)',
      WALK_INS: 'WALK-INS',
      ACTIVE: 'ACTIVE',
      ACTIONS: 'ACTIONS',
      EMPTY: 'No availability defined yet.',
    },
    DIALOG: {
      ADD_TITLE: 'Add availability',
      EDIT_TITLE: 'Edit availability',
      MODE: 'Repeats',
      MODE_WEEKLY: 'Weekly (recurring)',
      MODE_DATE: 'Specific date',
      WEEKDAY: 'Weekday',
      WEEKDAYS: 'Weekdays',
      DATE: 'Date',
      START: 'Start time',
      END: 'End time',
      DURATION: 'Slot duration (minutes)',
      WALK_INS: 'Accept walk-ins',
      ACTIVE: 'Active',
      SAVE: 'Save',
      CANCEL: 'Cancel',
    },
    DELETE_DIALOG: {
      TITLE: 'Delete availability',
      MESSAGE: 'Delete this availability window?',
      CONFIRM: 'Delete',
      DISMISS: 'Keep',
    },
    SERVICES_TABLE: {
      NAME: 'NAME',
      DESCRIPTION: 'DESCRIPTION',
      DURATION: 'DURATION (MIN)',
      ACTIVE: 'ACTIVE',
      ACTIONS: 'ACTIONS',
      EMPTY: 'No services defined yet.',
    },
    SERVICE_DIALOG: {
      ADD_TITLE: 'Add service',
      EDIT_TITLE: 'Edit service',
      NAME: 'Name',
      DESCRIPTION: 'Description',
      DURATION: 'Default duration (minutes)',
      ACTIVE: 'Active',
      SAVE: 'Save',
      CANCEL: 'Cancel',
    },
    ADD_SERVICE: 'Add service',
    SERVICE_AVAILABILITY_TITLE: 'Service availability',
    LINK_TABLE: {
      DOCTOR: 'DOCTOR',
      BRANCH: 'BRANCH',
      LINKED_USER: 'LINKED USER',
      ACTIONS: 'ACTIONS',
      EMPTY: 'No doctors found.',
      UNLINKED: 'Not linked',
    },
    LINK_DIALOG: {
      TITLE: 'Link provider account',
      USER: 'User',
      SAVE: 'Link',
      CANCEL: 'Cancel',
    },
    MESSAGES: {
      AVAIL_LOADING: 'Loading availability…',
      AVAIL_ERROR: 'Failed to load availability.',
      SAVE_SUCCESS: 'Availability saved.',
      SAVE_ERROR: 'Failed to save availability. Please try again.',
      DELETE_SUCCESS: 'Availability deleted.',
      DELETE_ERROR: 'Failed to delete availability. Please try again.',
      FORBIDDEN: 'You are not allowed to manage this availability.',
      SERVICE_SAVE_SUCCESS: 'Service saved.',
      SERVICE_SAVE_ERROR: 'Failed to save service. Please try again.',
      LINK_SUCCESS: 'Provider account linked.',
      LINK_ERROR: 'Failed to link provider account. Please try again.',
      VALIDATION: 'Please complete all required fields.',
    },
  },
  WEEKDAYS: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'] as string[],
  STATUS_LABELS: {
    scheduled: 'Scheduled',
    checked_in: 'Checked in',
    in_consultation: 'In consultation',
    completed: 'Completed',
    cancelled: 'Cancelled',
    no_show: 'No show',
  } as Record<string, string>,
  SOURCE_LABELS: { booked: 'Booked', walk_in: 'Walk-in' } as Record<string, string>,
  TYPE_LABELS: { consultation: 'Consultation', service: 'Service' } as Record<string, string>,
};
