// Centralised labels for the Outpatient (OPD) module. Pages import these rather
// than hardcoding strings (per src/config conventions).
export const OPD_LABELS = {
  APPOINTMENTS: {
    PAGE_TITLE: 'Appointments',
    SUBTITLE: 'View, book and manage outpatient appointments.',
    BOOK_BUTTON: 'Book Appointment',
    SEARCH_PLACEHOLDER: 'Search by patient name…',
    TABS: { UPCOMING: 'Upcoming', HISTORICAL: 'Historical' },
    FILTERS: {
      FROM: 'From',
      TO: 'To',
      DOCTOR: 'Doctor',
      SERVICE: 'Service',
      STATUS: 'Status',
      TYPE: 'Type',
      SOURCE: 'Source',
      ALL: 'All',
      CLEAR: 'Clear filters',
    },
    TABLE: {
      PATIENT: 'PATIENT',
      TYPE: 'TYPE',
      PROVIDER: 'PROVIDER / SERVICE',
      DATETIME: 'DATE & TIME',
      STATUS: 'STATUS',
      SOURCE: 'SOURCE',
      ACTIONS: 'ACTIONS',
    },
    ACTIONS: {
      VIEW: 'View',
      RESCHEDULE: 'Reschedule',
      CANCEL: 'Cancel',
      CHECK_IN: 'Check-in',
    },
    MESSAGES: {
      LOADING: 'Loading appointments…',
      ERROR: 'Failed to load appointments. Please try again.',
      EMPTY: 'No appointments found.',
      CHECK_IN_SUCCESS: 'Patient checked in.',
      CHECK_IN_ERROR: 'Failed to check in. Please try again.',
      CANCEL_SUCCESS: 'Appointment cancelled.',
      CANCEL_ERROR: 'Failed to cancel appointment. Please try again.',
      RESCHEDULE_SUCCESS: 'Appointment rescheduled.',
      RESCHEDULE_ERROR: 'Failed to reschedule. Please try again.',
      SLOT_TAKEN: 'That slot was just taken. Please pick another.',
    },
    RESCHEDULE_DIALOG: {
      TITLE: 'Reschedule appointment',
      DATE: 'New date',
      SLOT: 'New slot',
      NO_SLOTS: 'No slots available for this date.',
      CONFIRM: 'Reschedule',
      CANCEL: 'Cancel',
    },
    CANCEL_DIALOG: {
      TITLE: 'Cancel appointment',
      MESSAGE: 'Are you sure you want to cancel this appointment?',
      REASON: 'Reason (optional)',
      CONFIRM: 'Cancel appointment',
      DISMISS: 'Keep appointment',
    },
  },
  BOOKING: {
    PAGE_TITLE: 'Book Appointment',
    STEPS: { PATIENT: 'Patient', CATEGORY: 'Category', PROVIDER: 'Provider & Slot', CONFIRM: 'Confirm' },
    CATEGORY: {
      OPD: 'Outpatient (OPD)',
      IPD: 'Inpatient (IPD)',
      IPD_DISABLED: 'Coming soon',
      CONSULTATION: 'Consultation',
      SERVICE: 'Service',
      CHOOSE: 'Choose a category',
    },
    PROVIDER: {
      DOCTOR: 'Doctor',
      SERVICE: 'Service',
      DATE: 'Date',
      SLOTS: 'Available slots',
      NO_SLOTS: 'No slots available for this date.',
      PICK_PROVIDER: 'Select a doctor to view slots.',
      PICK_SERVICE: 'Select a service to view slots.',
    },
    CONFIRM: {
      TITLE: 'Review & confirm',
      PATIENT: 'Patient',
      TYPE: 'Type',
      PROVIDER: 'Provider / Service',
      DATETIME: 'Date & time',
      BOOK: 'Confirm booking',
    },
    NAV: { BACK: 'Back', NEXT: 'Next' },
    MESSAGES: {
      SUCCESS: 'Appointment booked.',
      ERROR: 'Failed to book appointment. Please try again.',
      SLOT_TAKEN: 'That slot was just taken. We refreshed the list — please pick another.',
    },
  },
  WALK_IN: {
    PAGE_TITLE: 'Walk-in Registration',
    SUBTITLE: 'Register a walk-in patient and issue a queue token.',
    DOCTOR: 'Doctor',
    DOCTOR_HINT: 'Select the doctor the patient will see.',
    REGISTER: 'Register Walk-in',
    TOKEN_TITLE: 'Walk-in registered',
    TOKEN_LABEL: 'Token number',
    TOKEN_DONE: 'Done',
    MESSAGES: {
      SUCCESS: 'Walk-in registered.',
      ERROR: 'Failed to register walk-in. Please try again.',
      NOT_ACCEPTING: 'This doctor is not accepting walk-ins right now.',
    },
  },
  PATIENT_PICKER: {
    SEARCH_PLACEHOLDER: 'Search patient by name, phone or MRN…',
    NO_RESULTS: 'No matching patients. Create a new one below.',
    SELECTED: 'Selected patient',
    CHANGE: 'Change',
    CREATE_TOGGLE: 'Create new patient',
    CREATE_TITLE: 'New patient',
    CREATE: 'Create patient',
    CANCEL: 'Cancel',
    FIELDS: {
      NAME: 'Full name',
      GENDER: 'Gender',
      PHONE: 'Phone',
      EMAIL: 'Email',
      MRN: 'MRN',
      ADDRESS: 'Address',
    },
    NAME_REQUIRED: 'Name is required.',
    CREATE_ERROR: 'Failed to create patient. Please try again.',
  },
  STATUS_LABELS: {
    scheduled: 'Scheduled',
    checked_in: 'Checked in',
    in_consultation: 'In consultation',
    completed: 'Completed',
    cancelled: 'Cancelled',
    no_show: 'No show',
  } as Record<string, string>,
  SOURCE_LABELS: { booked: 'Booked', walk_in: 'Walk-in' } as Record<string, string>,
  TYPE_LABELS: { consultation: 'Consultation', service: 'Service' } as Record<string, string>,
};
