export const PURCHASE_RETURN_LABELS = {
  LANDING: {
    TITLE: 'Supplier Purchase Return',
    SUBTITLE: 'Select batches to return to their supplier. Expired and near-expiry stock is shown first.',
    RETURNS_LOG_BUTTON: 'Returns Log',
    FILTERS: {
      PRODUCT: 'Product Name',
      PRODUCT_PLACEHOLDER: 'Search product...',
      TYPE: 'Type',
      BRAND: 'Brand',
      SUPPLIER: 'Supplier',
      SUPPLIER_PLACEHOLDER: 'All suppliers',
      EXPIRY_STATUS: 'Expiry Status',
      ALL: 'All',
    },
    TABLE: {
      SELECT: 'Select',
      PRODUCT: 'Product',
      BATCH: 'Batch No.',
      EXPIRY: 'Expiry',
      STATUS: 'Status',
      SUPPLIER: 'Supplier',
      STOCK: 'Qty on Hand',
      RECEIPT_QTY: 'Receipt Qty',
      PURCHASE_PRICE: 'Purchase Price',
      MRP: 'MRP ₹',
      RECEIPT: 'Invoice Number',
      RETURN_QTY: 'Return qty',
    },
    UNATTRIBUTABLE_TOOLTIP:
      'This batch cannot be attributed to a supplier and is not returnable.',
    UNATTRIBUTED: 'Unattributed',
    SUPPLIER_LOCK_PREFIX: 'Returning to ',
    SUPPLIER_LOCK_SUFFIX: ' — lines from other suppliers are locked',
    CLEAR_SELECTION: 'Clear selection',
    QTY_ERROR: 'Enter 1 to stock on hand',
    SELECTION_SUMMARY: (lines: number, units: number) =>
      `${lines} line${lines === 1 ? '' : 's'} · ${units} unit${units === 1 ? '' : 's'} selected`,
    RETURN_BUTTON: 'Return',
    LOADING: 'Loading returnable batches...',
    LOAD_FAILED: 'Failed to load returnable batches.',
    EMPTY: 'No returnable batches found',
    RETRY: 'Retry',
  },
  DETAILS: {
    TITLE: 'Purchase Return Details',
    SUMMARY: {
      SUPPLIER: 'Supplier',
      RECEIPTS: 'Original receipt(s)',
      RETURNED_BY: 'Returned by',
    },
    TABLE: {
      PRODUCT: 'Product',
      BATCH: 'Batch',
      EXPIRY: 'Expiry',
      RETURN_QTY: 'Return qty',
      UNIT_VALUE: 'Unit ₹',
      TAXABLE: 'Taxable ₹',
      GST: 'GST',
      LINE_TOTAL: 'Line total ₹',
    },
    GST_AT_FINALIZE: 'GST computed at finalize',
    ESTIMATED_NOTE: 'Estimated — final amounts are computed by the server at finalize.',
    OPTIONS: {
      GST_TREATMENT: 'GST treatment',
      VALUE_BASIS: 'Value basis',
      SETTLEMENT_MODE: 'Settlement mode',
    },
    UPI_REFERENCE: 'UPI transaction / UTR number',
    UPI_REFERENCE_PLACEHOLDER: 'Enter UPI transaction / UTR number (required)',
    CASH_REFERENCE: 'Receipt / voucher note',
    CASH_REFERENCE_PLACEHOLDER: 'Enter receipt / voucher note (optional)',
    CREDIT_NOTE_INFO:
      'The amount will be posted as a credit entry against the supplier in the Supplier Credit module and tracked in the Returns Log.',
    CREDIT_NOTE_UPLOAD_LABEL: 'Credit note photo/scan (optional)',
    UPLOAD_FAILED_NONFATAL:
      'Return recorded, but the credit note attachment failed to upload. You can add it from the Returns Log.',
    REASON: 'Reason',
    REASON_PLACEHOLDER: 'Reason for this return (optional)',
    NOTES: 'Notes',
    NOTES_PLACEHOLDER: 'Additional notes (optional)',
    TOTALS: {
      TITLE: 'Totals (Estimated)',
      TAXABLE: 'Taxable value',
      CGST: 'CGST',
      SGST: 'SGST',
      AMOUNT_OWED: 'Amount owed by supplier',
      EXCLUDES_GST: 'Excludes GST — computed at finalize',
    },
    NO_PURCHASE_PRICE_WARNING:
      'One or more selected batches have no attributed purchase price. Switch the value basis to MRP to proceed.',
    FINALIZE: 'Finalize Return',
    CANCEL: 'Cancel',
    CONFIRM: {
      TITLE: 'Confirm Purchase Return',
      CONFIRM_LABEL: 'Finalize',
      CANCEL_LABEL: 'Cancel',
      MESSAGE: (lines: number, units: number, supplier: string) =>
        `You are returning ${lines} line${lines === 1 ? '' : 's'} (${units} unit${
          units === 1 ? '' : 's'
        }) to ${supplier}. Stock will be permanently decremented. This action cannot be undone.`,
    },
    SUCCESS: {
      TITLE: 'Purchase return submitted',
      RETURN_NUMBER: 'Return number',
      SUPPLIER: 'Supplier',
      LINES_UNITS: 'Lines / units',
      TAXABLE: 'Taxable value',
      CGST: 'CGST',
      SGST: 'SGST',
      TOTAL: 'Amount owed by supplier',
      SETTLEMENT: 'Settlement mode',
      STATUS: 'Status',
      CREDIT_BANNER: (balance: string) =>
        `A credit note was posted against the supplier. New supplier credit balance: ${balance}.`,
      CREDIT_BANNER_NO_BALANCE: 'A credit note was posted against the supplier.',
      ATTACHMENT: 'Credit note attachment',
      ATTACHMENT_UPLOADED: 'Uploaded ✓',
      ATTACHMENT_NOT_ATTACHED: 'Not attached',
      START_NEW: 'Start new return',
      VIEW_LOG: 'View Returns Log',
    },
    SUBMIT_FAILED: 'Failed to submit the purchase return.',
  },
  UPLOAD: {
    PROMPT: 'Upload credit note',
    FILE_TOO_LARGE: (maxMb: number) => `File must be ${maxMb} MB or smaller.`,
    INVALID_TYPE: 'Only PNG, JPEG or PDF files are allowed.',
    REMOVE: 'Remove file',
  },
  LOG: {
    TITLE: 'Purchase Returns Log',
    BACK_BUTTON: 'Back to Purchase Return',
    SEARCH_PLACEHOLDER: 'Search by return ref or supplier...',
    STATUS_FILTER: 'Status',
    ALL_STATUSES: 'All',
    TABLE: {
      RETURN_REF: 'Return ref',
      DATE: 'Date',
      SUPPLIER: 'Supplier',
      LINES_UNITS: 'Lines / units',
      AMOUNT: 'Amount owed ₹',
      SETTLEMENT: 'Settlement mode',
      STATUS: 'Status',
      ACTION: 'Action',
    },
    RECORD_CREDIT_BUTTON: 'Record credit received',
    CREDIT_RECEIVED_TEXT: (date: string, ref: string) => `Credit received ${date}${ref ? ` · ${ref}` : ''}`,
    SETTLED_TEXT: (mode: string) => `Settled via ${mode}`,
    LOADING: 'Loading returns...',
    LOAD_FAILED: 'Failed to load supplier returns.',
    EMPTY: 'No supplier returns yet',
    TRUNCATED: (shown: number, total: number) => `Showing first ${shown} of ${total} returns`,
    CREDIT_MODAL: {
      TITLE: 'Record Credit Received',
      AMOUNT: 'Amount',
      DATE: 'Date',
      REFERENCE: 'Reference',
      REFERENCE_PLACEHOLDER: 'Credit note / reference number (optional)',
      SUBMIT: 'Record Credit',
      SUCCESS: 'Credit received recorded.',
      AMOUNT_ERROR: 'Enter an amount greater than 0.',
      FAILED: 'Failed to record credit received.',
      ATTACHMENT: 'Credit note photo/scan',
      ATTACHMENT_REPLACE: 'Replace credit note photo/scan',
      EXISTING_FILE: 'Attached credit note',
      VIEW: 'View',
      UPLOAD_FAILED_NONFATAL: 'Credit recorded, but the attachment failed to upload.',
    },
    VIEW_FILE_FAILED: 'Failed to open the credit note file.',
    DETAILS_MODAL: {
      TITLE: 'Return Details',
      LOADING: 'Loading return details...',
      FAILED: 'Failed to load return details.',
      DATE: 'Date',
      RETURNED_BY: 'Returned by',
      GST_TREATMENT: 'GST treatment',
      VALUE_BASIS: 'Value basis',
      SETTLEMENT: 'Settlement',
      REFERENCE: 'Reference',
      REASON: 'Reason',
      NOTES: 'Notes',
      CREDIT_RECEIVED: 'Credit received',
      CREDIT_NOTE_FILE: 'Credit note file',
      TAXABLE: 'Taxable value',
      CGST: 'CGST',
      SGST: 'SGST',
      TOTAL: 'Amount owed',
      LINES: {
        PRODUCT: 'Product',
        BATCH: 'Batch',
        EXPIRY: 'Expiry',
        QTY: 'Qty',
        UNIT_VALUE: 'Unit ₹',
        GST_RATE: 'GST %',
        TOTAL: 'Line total ₹',
      },
    },
  },
} as const;
