export const SALES_TAX_REPORT_LABELS = {
  PAGE: {
    TITLE: 'Sales Tax Report',
    SUBTITLE:
      'GST breakdown per sale line (CGST / SGST / IGST) with range-level aggregates. Selling price is tax-inclusive.',
    DOWNLOAD_CSV: 'Download CSV',
    CSV_FILENAME_PREFIX: 'sales_tax_report',
  },
  DISCOVERY_CARD: {
    TITLE: 'Sales Tax Report',
    DESCRIPTION:
      'Per-line GST extraction (CGST / SGST / IGST) plus prominent taxable, tax and sales aggregates.',
    ACTION: 'View Report',
  },
  TABS: {
    OVERVIEW: 'Overview',
    PRODUCT: 'Product-wise',
    HSN: 'HSN-wise',
    INVOICE: 'Invoice-wise',
  },
  FILTER: {
    PRODUCT_LABEL: 'Product',
    PRODUCT_ALL: 'All Products',
    PATIENT_TYPE_LABEL: 'Patient Type',
    PATIENT_TYPE_ALL: 'All Patient Types',
    PATIENT_TYPE_INPATIENT: 'In Patient',
    PATIENT_TYPE_OUTPATIENT: 'Out Patient',
    HSN_LABEL: 'HSN Code',
    HSN_ALL: 'All HSN Codes',
  },
  SECTIONS: {
    TAX_BY_DATE: 'Tax Collected by Date',
    TOP_PRODUCTS_BY_TAXABLE: 'Top Products by Taxable Value',
    TAX_COMPOSITION: 'Tax Composition',
  },
  CHART_SERIES: {
    TAX: 'Tax (₹)',
    TAXABLE: 'Taxable Value (₹)',
  },
  AXIS: {
    DATE: 'Date',
    TAX: 'Tax (₹)',
    PRODUCT: 'Product',
    TAXABLE: 'Taxable Value (₹)',
  },
  TAX_TYPES: {
    CGST: 'CGST',
    SGST: 'SGST',
    IGST: 'IGST',
  },
  EMPTY_CHART: 'No data for the selected period.',
  SUMMARY: {
    TITLE: 'Range Aggregates',
    TOTAL_TAXABLE: 'Total Taxable Value',
    TOTAL_CGST: 'Total CGST',
    TOTAL_SGST: 'Total SGST',
    TOTAL_IGST: 'Total IGST',
    TOTAL_TAX: 'Total Tax',
    TOTAL_SALES: 'Total Net Sale Value',
    ROUND_OFF: 'Round-off',
    TOTAL_MRP_VALUE: 'Total MRP Value',
    LINES: 'Lines',
    PRODUCTS: 'Products',
    INVOICES: 'Invoices',
    UNIQUE_HSN: 'Unique HSN Codes',
  },
  TABLE: {
    INVOICE_NUMBER: 'Invoice #',
    SALE_DATE: 'Sale Date',
    PRODUCT: 'Product',
    CODE: 'Code',
    HSN: 'HSN',
    BATCH_NUMBER: 'Batch #',
    CUSTOMER_DETAILS: 'Customer Details',
    QTY: 'Qty',
    MRP: 'MRP',
    SP: 'SP',
    TAXABLE_VALUE: 'Taxable Value',
    DISCOUNT: 'Discount',
    CGST_RATE: 'CGST%',
    SGST_RATE: 'SGST%',
    IGST_RATE: 'IGST%',
    CGST_AMT: 'CGST ₹',
    SGST_AMT: 'SGST ₹',
    IGST_AMT: 'IGST ₹',
    TOTAL_TAX: 'Total Tax',
    LINE_TOTAL: 'Line Total',
  },
  TABLE_HSN: {
    HSN: 'HSN Code',
    LINES: 'Lines',
    PRODUCTS: 'Products',
    QTY: 'Qty',
    TAXABLE_VALUE: 'Taxable Value',
    DISCOUNT: 'Discount',
    CGST_RATE: 'CGST%',
    SGST_RATE: 'SGST%',
    IGST_RATE: 'IGST%',
    CGST_AMT: 'CGST ₹',
    SGST_AMT: 'SGST ₹',
    IGST_AMT: 'IGST ₹',
    TOTAL_TAX: 'Total Tax',
    TOTAL: 'Total',
  },
  TABLE_INVOICE: {
    INVOICE_NUMBER: 'Invoice No',
    SALE_DATE: 'Date',
    CUSTOMER: 'Customer',
    LINES: 'Lines',
    QTY: 'Qty',
    TAXABLE_VALUE: 'Taxable Value',
    DISCOUNT: 'Discount',
    CGST_AMT: 'CGST',
    SGST_AMT: 'SGST',
    IGST_AMT: 'IGST',
    TOTAL_TAX: 'Total Tax',
    ROUND_OFF: 'Round-off',
    INVOICE_TOTAL: 'Invoice Total',
  },
  TOTALS_ROW_LABEL: 'Total',
  EMPTY_TABLE: 'No sales for the selected period.',
} as const;

export type SalesTaxReportLabels = typeof SALES_TAX_REPORT_LABELS;
