export const SETTINGS_LABELS = {
  PAGE_TITLE: 'System Settings',
  SECTIONS: {
    GENERAL: {
      TITLE: 'General Settings',
      DESC: 'Configure basic application preferences.',
    },
    USER_PRIVILEGE: {
      TITLE: 'User privilege mapping',
      DESC: 'Manage permissions for users',
    },
    DATA_PRIVACY: {
      TITLE: 'Data & Privacy',
      DESC: 'Manage your data and privacy settings.',
    },
    MODULES: {
      TITLE: 'Modules',
      DESC: 'Enable or disable modules for your organization.',
      CORE_TAG: 'Always on',
      LOADING: 'Loading modules...',
      LOAD_ERROR: 'Could not load modules.',
      TOGGLE_ERROR: 'Could not update the module. Please try again.',
      ENABLED_SUCCESS: (label: string) => `${label} enabled.`,
      DISABLED_SUCCESS: (label: string) => `${label} disabled.`,
    },
    PHARMACY_PROFILE: {
      TITLE: 'Pharmacy Profile',
      DESC: 'Name, legal details and logo shown across the app and on printed invoices.',
      LOADING: 'Loading profile...',
      LOAD_ERROR: 'Could not load the pharmacy profile.',
      NO_ORG_NOTE: 'No organization is linked to your account yet.',
      READ_ONLY_NOTE: 'Only an owner or admin can edit the pharmacy profile.',
      SAVE_BUTTON: 'Save Changes',
      SAVE_SUCCESS: 'Pharmacy profile updated.',
      SAVE_ERROR: 'Could not update the pharmacy profile.',
      NAME_REQUIRED: 'Pharmacy name is required.',
      FIELDS: {
        NAME: 'Pharmacy Name',
        LEGAL_NAME: 'Legal Name',
        ADDRESS: 'Address',
        DL_NUMBERS: 'Drug License Numbers',
        GSTIN: 'GSTIN',
        PHONE: 'Phone',
      },
      LOGO: {
        HEADING: 'Logo',
        CURRENT_CAPTION: 'Current logo',
        DEFAULT_CAPTION: 'Default logo',
        PENDING_CAPTION: 'Pending upload',
        CHOOSE_BUTTON: 'Choose image',
        UPLOAD_BUTTON: 'Save logo',
        REMOVE_BUTTON: 'Remove logo',
        HINT: 'PNG, JPEG, WebP or SVG. Max 1MB.',
        UPLOAD_SUCCESS: 'Logo updated.',
        UPLOAD_ERROR: 'Could not update the logo.',
        REMOVE_SUCCESS: 'Logo removed.',
        REMOVE_ERROR: 'Could not remove the logo.',
        INVALID_TYPE: 'Unsupported file type. Use PNG, JPEG, WebP or SVG.',
        OVERSIZE: 'Image is too large. Maximum size is 1MB.',
        READ_ERROR: 'Could not read the selected file.',
        REMOVE_CONFIRM_TITLE: 'Remove logo?',
        REMOVE_CONFIRM_MESSAGE: 'Remove the current logo? The default logo will be shown instead.',
      },
    },
    DAILY_REPORTS: {
      TITLE: 'Daily Report Recipients',
      DESC: 'Manage who receives automated daily activity reports.',
      ADD_PLACEHOLDER: 'Add new recipient email',
      ADD_BUTTON: 'Add Recipient',
      SEND_NOW_BUTTON: 'Send now',
      LOADING: 'Loading recipients...',
      EMPTY: 'No recipients yet. Add an email below.',
      LOAD_ERROR: 'Could not load recipients.',
      INVALID_EMAIL: 'Please enter a valid email address.',
      ADD_SUCCESS: 'Recipient added.',
      ADD_ERROR: 'Could not add recipient.',
      REMOVE_SUCCESS: 'Recipient removed.',
      REMOVE_ERROR: 'Could not remove recipient.',
      SEND_ERROR: 'Could not send the daily report.',
      SEND_SUCCESS: (sent: number) => `Sent to ${sent} recipient(s).`,
      SEND_SUCCESS_WITH_FAILED: (sent: number, failed: number) =>
        `Sent to ${sent} recipient(s), ${failed} failed.`,
    },
  },
  SAVE_BUTTON: 'Save Changes',
} as const;

export type SettingsLabels = typeof SETTINGS_LABELS;

