export const SETTINGS_LABELS = {
  PAGE_TITLE: 'System Settings',
  SECTIONS: {
    GENERAL: {
      TITLE: 'General Settings',
      DESC: 'Configure basic application preferences.',
    },
    USER_PRIVILEGE: {
      TITLE: 'User privilege mapping',
      DESC: 'Manage permissions for users',
    },
    DATA_PRIVACY: {
      TITLE: 'Data & Privacy',
      DESC: 'Manage your data and privacy settings.',
    },
    MODULES: {
      TITLE: 'Modules',
      DESC: 'Enable or disable modules for your organization.',
      CORE_TAG: 'Always on',
      LOADING: 'Loading modules...',
      LOAD_ERROR: 'Could not load modules.',
      TOGGLE_ERROR: 'Could not update the module. Please try again.',
      ENABLED_SUCCESS: (label: string) => `${label} enabled.`,
      DISABLED_SUCCESS: (label: string) => `${label} disabled.`,
    },
    PHARMACY_PROFILE: {
      TITLE: 'Pharmacy Profile',
      DESC: 'Name, legal details and logo shown across the app and on printed invoices.',
      LOADING: 'Loading profile...',
      LOAD_ERROR: 'Could not load the pharmacy profile.',
      NO_ORG_NOTE: 'No organization is linked to your account yet.',
      READ_ONLY_NOTE: 'Only an owner or admin can edit the pharmacy profile.',
      SAVE_BUTTON: 'Save Changes',
      SAVE_SUCCESS: 'Pharmacy profile updated.',
      SAVE_ERROR: 'Could not update the pharmacy profile.',
      NAME_REQUIRED: 'Pharmacy name is required.',
      FIELDS: {
        NAME: 'Pharmacy Name',
        LEGAL_NAME: 'Legal Name',
        ADDRESS: 'Address',
        DL_NUMBERS: 'Drug License Numbers',
        GSTIN: 'GSTIN',
        PHONE: 'Phone',
      },
      LOGO: {
        HEADING: 'Logo',
        CURRENT_CAPTION: 'Current logo',
        DEFAULT_CAPTION: 'Default logo',
        PENDING_CAPTION: 'Pending upload',
        CHOOSE_BUTTON: 'Choose image',
        UPLOAD_BUTTON: 'Save logo',
        REMOVE_BUTTON: 'Remove logo',
        HINT: 'PNG, JPEG, WebP or SVG. Max 1MB.',
        UPLOAD_SUCCESS: 'Logo updated.',
        UPLOAD_ERROR: 'Could not update the logo.',
        REMOVE_SUCCESS: 'Logo removed.',
        REMOVE_ERROR: 'Could not remove the logo.',
        INVALID_TYPE: 'Unsupported file type. Use PNG, JPEG, WebP or SVG.',
        OVERSIZE: 'Image is too large. Maximum size is 1MB.',
        READ_ERROR: 'Could not read the selected file.',
        REMOVE_CONFIRM_TITLE: 'Remove logo?',
        REMOVE_CONFIRM_MESSAGE: 'Remove the current logo? The default logo will be shown instead.',
      },
    },
    DOCUMENT_NUMBERING: {
      TITLE: 'Document Numbering',
      DESC: 'Set the number format for each document your pharmacy issues.',
      READ_ONLY_NOTE: 'Only an owner or admin can edit document numbering.',
      LOADING: 'Loading document numbering...',
      LOAD_ERROR: 'Could not load document numbering.',
      // Display names for the four series, keyed by the API's doc_type.
      DOC_TYPES: {
        sales_invoice: 'Sales Invoice',
        sales_return: 'Sales Return',
        receipt: 'Receipt / GRN',
        purchase_return: 'Purchase Return',
      },
      STATUS_ON: 'Custom',
      STATUS_OFF: 'Built-in',
      SUMMARY_DEFAULT: 'Using the built-in numbering',
      // A SAMPLE of the format (rendered by the server from seq_start ?? reset_to for a
      // document dated today) — NOT the live counter, so it must never say "Next:".
      SUMMARY_EXAMPLE: (sample: string) => `Example: ${sample}`,
      EXPAND_ARIA: (docLabel: string) => `Configure ${docLabel} numbering`,
      ENABLE_LABEL: 'Use a custom number format',
      TEMPLATE_LABEL: 'Number format',
      TEMPLATE_HELP:
        'Tokens: {YY} 2-digit year, {YYYY} 4-digit year, {MM} month, {SEQ:n} zero-padded sequence (width n), {SEQ} unpadded. Everything else is literal; exactly one SEQ token is required.',
      TEMPLATE_EXAMPLE: 'Example: SI-EL-{YY}-{SEQ:6} continuing from 2296 becomes SI-EL-26-002296.',
      CUTOVER_HEADING: 'Applies once — moving over from your old system',
      CUTOVER_DESC:
        'The next document gets this number, then counting continues from it. It affects the current period only; later periods restart at the number below.',
      START_LABEL: 'Continue numbering from',
      // No placeholder: the MUI label occupies the empty field, so one would never render —
      // the "leave blank" guidance lives in the helper text below instead.
      START_HELP: 'Applied once when you save, then cleared — leave blank to keep counting and the running count is untouched.',
      RECURRING_HEADING: 'Applies every period — the recurring reset',
      RECURRING_DESC:
        'Choose how often the sequence starts over, and the number each new period begins with.',
      RESET_LABEL: 'Reset cycle',
      RESET_NONE: 'Never reset',
      RESET_MONTHLY: 'Every month',
      RESET_ANNUAL: 'Every year',
      ANCHOR_MONTH_LABEL: 'Year starts in',
      ANCHOR_DAY_LABEL: 'on day',
      ANCHOR_HELP: 'Defaults to 1 April, the Indian financial year.',
      RESET_TO_LABEL: 'Every new period restarts at',
      RESET_TO_HELP: 'Leave blank to keep the saved value.',
      PREVIEW_PREFIX: (docLabel: string) => `Example ${docLabel} number`,
      SAVE_BUTTON: 'Save',
      SAVE_SUCCESS: (docLabel: string) => `${docLabel} numbering updated.`,
      SAVE_ERROR: 'Could not update document numbering.',
      TEMPLATE_REQUIRED: 'A number format is required when custom numbering is on.',
      START_INVALID: 'Continue-from number must be a whole number of 0 or more.',
      RESET_TO_INVALID: 'Restart number must be a whole number of 0 or more.',
      ANCHOR_DAY_INVALID: 'Anchor day must be a whole number between 1 and 31.',
      MONTHS: [
        'January', 'February', 'March', 'April', 'May', 'June',
        'July', 'August', 'September', 'October', 'November', 'December',
      ],
    },
    DAILY_REPORTS: {
      TITLE: 'Daily Report Recipients',
      DESC: 'Manage who receives automated daily activity reports.',
      ADD_PLACEHOLDER: 'Add new recipient email',
      ADD_BUTTON: 'Add Recipient',
      SEND_NOW_BUTTON: 'Send now',
      LOADING: 'Loading recipients...',
      EMPTY: 'No recipients yet. Add an email below.',
      LOAD_ERROR: 'Could not load recipients.',
      INVALID_EMAIL: 'Please enter a valid email address.',
      ADD_SUCCESS: 'Recipient added.',
      ADD_ERROR: 'Could not add recipient.',
      REMOVE_SUCCESS: 'Recipient removed.',
      REMOVE_ERROR: 'Could not remove recipient.',
      SEND_ERROR: 'Could not send the daily report.',
      SEND_SUCCESS: (sent: number) => `Sent to ${sent} recipient(s).`,
      SEND_SUCCESS_WITH_FAILED: (sent: number, failed: number) =>
        `Sent to ${sent} recipient(s), ${failed} failed.`,
    },
  },
  SAVE_BUTTON: 'Save Changes',
} as const;

export type SettingsLabels = typeof SETTINGS_LABELS;

