export const USER_PROFILE_LABELS = {
  PAGE_TITLE: 'User Profile',
  DASH: '—',
  HEADER: {
    USERNAME_PREFIX: '@',
  },
  ERROR: {
    PROFILE: 'Unable to load your profile. Please try again later.',
    ACTIVITY: 'Unable to load recent activity. Please try again later.',
  },
  EDIT: {
    BUTTON: 'Edit profile',
    SAVE: 'Save',
    CANCEL: 'Cancel',
    SAVING: 'Saving…',
    SUCCESS: 'Profile updated successfully.',
    ERROR: 'Failed to update profile. Please try again.',
    FIRST_NAME: 'First name',
    LAST_NAME: 'Last name',
    MOBILE: 'Mobile',
    IDENTITY_SELECT_PLACEHOLDER: 'Select Identity Document',
    // Same 0/1 mapping + labels as the admin create-user form (AddUserModal).
    IDENTITY_OPTION_AADHAAR: 'Aadhar Card',
    IDENTITY_OPTION_DRIVING_LICENCE: 'Driving Licence',
    IDENTITY_NUMBER_HINT: 'Leave blank to keep your current number.',
  },
  SECTIONS: {
    ACCOUNT: {
      TITLE: 'Account',
      EMAIL: 'Email',
      EMAIL_HINT: 'To change your email, please contact an administrator.',
      MEMBER_SINCE: 'Member since',
      LAST_LOGIN: 'Last login',
    },
    CONTACT: {
      TITLE: 'Contact',
      MOBILE: 'Mobile',
      ADDRESS_LINE1: 'Address line 1',
      ADDRESS_LINE2: 'Address line 2',
      CITY: 'City',
      STATE: 'State',
      POSTAL_CODE: 'Postal code',
      COUNTRY: 'Country',
    },
    IDENTITY: {
      TITLE: 'Identity Document',
      DOCUMENT_TYPE: 'Document type',
      DOCUMENT_NUMBER: 'Document number',
    },
    DOCUMENTS: {
      TITLE: 'Documents',
      ALLOWED_HINT: 'PNG, JPEG or PDF. Max 50MB.',
      ID_DOCUMENT: 'Identity document',
      PHARMACIST_CERTIFICATE: 'Pharmacist certificate',
      NOT_UPLOADED: 'Not uploaded',
      VIEW: 'View',
      UPLOAD: 'Upload',
      REPLACE: 'Replace',
      UPLOADING: 'Uploading…',
      UPLOAD_SUCCESS: 'Document uploaded successfully.',
      UPLOAD_ERROR: 'Failed to upload the document. Please try again.',
      DOWNLOAD_ERROR: 'Failed to download the document. Please try again.',
      FILE_TOO_LARGE: 'File is too large. Maximum size is 50MB.',
      UNSUPPORTED_TYPE: 'Unsupported file type. Allowed: PNG, JPEG, PDF.',
    },
    RECENT_ACTIVITY: {
      TITLE: 'Recent Activity',
      EMPTY: 'No recent activity.',
      COL_MODULE: 'Module',
      COL_EVENT_TYPE: 'Event',
      COL_EVENT_TIME: 'Time',
      COL_EVENT_DETAILS: 'Details',
    },
  },
} as const;

export type UserProfileLabels = typeof USER_PROFILE_LABELS;
