export const AUDIT_LOG_CONSTANTS = {
  LAYOUT: {
    PAGE_PADDING: 3,
    PAGE_GAP: 3,
    TITLE_MARGIN_BOTTOM: 1,
    ACTION_BAR_MARGIN_BOTTOM: 1,
    ACTION_BAR_GAP: 2,
    TABLE_MARGIN_TOP: '8px',
    BACK_BUTTON_POSITION: {
      position: 'absolute' as const,
      bottom: 24,
      right: 24,
    },
  },
  TYPOGRAPHY: {
    TITLE_VARIANT: 'h4' as const,
    TITLE_FONT_WEIGHT: 700,
    SUBTITLE_FONT_SIZE: '14px',
    SUBTITLE_COLOR: '#728197',
  },
  SEARCH_FIELD: {
    MAX_WIDTH: 400,
    HEIGHT: '40px',
    BORDER_RADIUS: '12px',
    BACKGROUND_COLOR: '#ffffff',
    DEFAULT_BORDER: '1px solid #9AA8bc',
    HOVER_BORDER: '1px solid #5C17E5',
    FOCUS_BORDER: '2px solid #5C17E5',
    ICON_COLOR: '#728197',
    ICON_SIZE: '20px',
  },
  BUTTON: {
    FILTERS: {
      BACKGROUND_COLOR: '#ffffff',
      COLOR: '#1A212B',
      HOVER_BACKGROUND: '#F5F5F5',
      PADDING_X: 2,
      TEXT_TRANSFORM: 'none' as const,
      BORDER_RADIUS: '12px',
      BORDER: '1px solid #D7DFEA',
      HEIGHT: '40px',
    },
    DROPDOWN: {
      BACKGROUND_COLOR: '#ffffff',
      COLOR: '#1A212B',
      HOVER_BACKGROUND: '#F5F5F5',
      PADDING_X: 2,
      TEXT_TRANSFORM: 'none' as const,
      BORDER_RADIUS: '12px',
      BORDER: '1px solid #D7DFEA',
      HEIGHT: '40px',
      MIN_WIDTH: '40px',
    },
    BACK: {
      BACKGROUND_COLOR: '#5C17E5',
      COLOR: 'white',
      HOVER_BACKGROUND: '#4a12b8',
      PADDING_X: 3,
      TEXT_TRANSFORM: 'none' as const,
      BORDER_RADIUS: '12px',
      HEIGHT: '40px',
      MIN_WIDTH: '100px',
    },
  },
  TABLE: {
    CONTAINER_BACKGROUND: '#ffffff',
    CONTAINER_BORDER_RADIUS: '12px',
    CONTAINER_BORDER: '1px solid #E0E0E0',
    HEADER_BACKGROUND: '#F5F5F5',
    HEADER_PADDING: '2px 12px',
    HEADER_FONT_FAMILY: "'Lexend', sans-serif",
    HEADER_FONT_WEIGHT: 500,
    HEADER_FONT_SIZE: '16px',
    HEADER_LINE_HEIGHT: '24px',
    HEADER_COLOR: '#1A212B',
    CELL_PADDING: '8px 12px',
    ROW_BACKGROUND_ODD: '#FFFFFF',
    ROW_BACKGROUND_EVEN: '#FAFAFA',
    CELL_BORDER: 'none',
    HEADER_CELL_BORDER_RIGHT: '1px solid #E0E0E0',
    ROW_BORDER: '1px solid #E0E0E0',
    ROW_HOVER_BACKGROUND: '#F0F0F0',
    TEXT_COLOR_PRIMARY: '#1A212B',
    TEXT_COLOR_SECONDARY: '#728197',
  },
  AVATAR: {
    SIZE: 30,
    FONT_SIZE: '13px',
    BACKGROUND_COLOR: '#5C17E5',
    GAP: 1.5,
  },
  USER_INFO: {
    NAME_FONT_SIZE: '14px',
    NAME_FONT_WEIGHT: 400,
    NAME_LINE_HEIGHT: 1.25,
  },
  CHIP: {
    ACCESS_LEVEL: {
      HEIGHT: '24px',
      FONT_SIZE: '14px',
      FONT_WEIGHT: 400,
      BACKGROUND_COLOR: '#ffffff',
      COLOR: '#1A212B',
      LABEL_PADDING: '0 7px',
    },
  },
  PAGINATION: {
    ROWS_PER_PAGE: 10,
    DEFAULT_SORT_KEY: 'eventTime',
    DEFAULT_SORT_DIRECTION: 'desc' as const,
  },
} as const;

export type AuditLogConstants = typeof AUDIT_LOG_CONSTANTS;

