export const USERS_CONSTANTS = {
  LAYOUT: {
    PAGE_PADDING: 3,
    PAGE_GAP: 3,
    TITLE_MARGIN_BOTTOM: 1,
    ACTION_BAR_MARGIN_BOTTOM: 1,
    ACTION_BAR_GAP: 2,
    TABLE_MARGIN_TOP: '8px',
  },
  TYPOGRAPHY: {
    TITLE_VARIANT: 'h4' as const,
    TITLE_FONT_WEIGHT: 700,
    SUBTITLE_FONT_SIZE: '14px',
    SUBTITLE_COLOR: '#728197',
  },
  SEARCH_FIELD: {
    MAX_WIDTH: 400,
    HEIGHT: '40px',
    BORDER_RADIUS: '12px',
    BACKGROUND_COLOR: '#ffffff',
    DEFAULT_BORDER: '1px solid #9AA8bc',
    HOVER_BORDER: '1px solid #5C17E5',
    FOCUS_BORDER: '2px solid #5C17E5',
    ICON_COLOR: '#728197',
    ICON_SIZE: '20px',
  },
  BUTTON: {
    BACKGROUND_COLOR: '#5C17E5',
    COLOR: 'white',
    HOVER_BACKGROUND: '#4a12b8',
    PADDING_X: 3,
    TEXT_TRANSFORM: 'none' as const,
    BORDER_RADIUS: '10px',
  },
  TABLE: {
    CONTAINER_BACKGROUND: '#ffffff',
    CONTAINER_BORDER_RADIUS: '12px',
    CONTAINER_BORDER: '1px solid #E0E0E0',
    HEADER_BACKGROUND: '#F5F5F5',
    HEADER_PADDING: '8px 12px',
    HEADER_FONT_FAMILY: "'Lexend', sans-serif",
    HEADER_FONT_WEIGHT: 500,
    HEADER_FONT_SIZE: '16px',
    HEADER_LINE_HEIGHT: '20px',
    HEADER_COLOR: '#1A212B',
    CELL_PADDING: '8px 12px',
    ROW_BACKGROUND_ODD: '#FFFFFF',
    ROW_BACKGROUND_EVEN: '#FAFAFA',
    CELL_BORDER: 'none',
    HEADER_CELL_BORDER_RIGHT: '1px solid #E0E0E0',
    ROW_BORDER: '1px solid #E0E0E0',
  },
  AVATAR: {
    SIZE: 30,
    FONT_SIZE: '13px',
    BACKGROUND_COLOR: '#5C17E5',
    GAP: 1.5,
  },
  USER_INFO: {
    NAME_FONT_SIZE: '13px',
    NAME_FONT_WEIGHT: 500,
    NAME_LINE_HEIGHT: 1.25,
    EMAIL_FONT_SIZE: '11px',
    EMAIL_COLOR: '#728197',
    EMAIL_LINE_HEIGHT: 1.15,
  },
  CHIP: {
    ROLE: {
      HEIGHT: '24px',
      FONT_SIZE: '11px',
      FONT_WEIGHT: 500,
      BACKGROUND_COLOR: '#e8d5ff',
      COLOR: '#5C17E5',
      LABEL_PADDING: '0 7px',
    },
    STATUS: {
      HEIGHT: '24px',
      FONT_SIZE: '11px',
      FONT_WEIGHT: 500,
      LABEL_PADDING: '0 7px',
      ACTIVE: {
        BACKGROUND: '#d4edda',
        COLOR: '#155724',
      },
      PENDING: {
        BACKGROUND: '#fff3cd',
        COLOR: '#856404',
      },
      INACTIVE: {
        BACKGROUND: '#f8d7da',
        COLOR: '#721c24',
      },
    },
  },
  LAST_LOGIN: {
    FONT_SIZE: '12px',
    COLOR: '#728197',
    LINE_HEIGHT: 1.25,
  },
  ACTIONS: {
    GAP: 0.5,
    EDIT_COLOR: '#1A212B',
    DELETE_COLOR: '#1A212B',
    ICON_PADDING: '4px',
    ICON_SIZE: '18px',
  },
  PAGINATION: {
    ROWS_PER_PAGE: 10,
    DEFAULT_SORT_KEY: 'name',
    DEFAULT_SORT_DIRECTION: 'asc' as const,
  },
  SCROLLBAR: {
    HEIGHT: '8px',
    TRACK_COLOR: '#f1f1f1',
    TRACK_BORDER_RADIUS: '4px',
    THUMB_COLOR: '#c1c1c1',
    THUMB_BORDER_RADIUS: '4px',
    THUMB_HOVER_COLOR: '#a8a8a8',
  },
} as const;

export type UsersConstants = typeof USERS_CONSTANTS;

